import {BRL,escapeHtml} from '../utils/helpers.js';
export class CheckoutView{
  constructor(model,cartService,checkoutService,handlers){this.model=model;this.cart=cartService;this.checkout=checkoutService;this.handlers=handlers;}
  render(state){
    const customer={...this.model.customer(),...(state.customer||{})}; const quote=this.checkout.quote(state.shipping,state.coupon); const lines=this.cart.lines();
    return `<section><h1 class="page-title">Finalizar venda</h1><p class="page-subtitle">Revise os dados e confirme o pedido.</p>
    <form id="checkoutForm" class="section">
      <div class="panel"><h2>1. Dados do cliente</h2><div class="grid-2 section"><div class="field"><label>Nome</label><input name="name" required value="${escapeHtml(customer.name)}"></div><div class="field"><label>E-mail</label><input name="email" type="email" required value="${escapeHtml(customer.email)}"></div><div class="field"><label>Telefone</label><input name="phone" required value="${escapeHtml(customer.phone)}"></div><div class="field"><label>CEP</label><input name="zip" required value="${escapeHtml(customer.zip)}"></div><div class="field"><label>Endereço</label><input name="address" required value="${escapeHtml(customer.address)}"></div><div class="field"><label>Número</label><input name="number" required value="${escapeHtml(customer.number)}"></div><div class="field full"><label>Cidade</label><input name="city" required value="${escapeHtml(customer.city)}"></div></div></div>
      <div class="panel section"><h2>2. Entrega</h2><div class="radio-grid section"><label class="radio-option"><input type="radio" name="shipping" value="standard" ${state.shipping==='standard'?'checked':''}><span><strong>Normal</strong><br><small>R$ ${quoteStandard(quote,state).toFixed(2).replace('.',',')} · grátis acima de R$ 199</small></span></label><label class="radio-option"><input type="radio" name="shipping" value="express" ${state.shipping==='express'?'checked':''}><span><strong>Expressa</strong><br><small>Entrega prioritária — valor calculado no resumo</small></span></label></div></div>
      <div class="panel section"><h2>3. Pagamento</h2><div class="radio-grid section"><label class="radio-option"><input type="radio" name="paymentMethod" value="pix" ${state.paymentMethod==='pix'?'checked':''}><span><strong>PIX</strong><br><small>Confirmação imediata, demonstrativa.</small></span></label><label class="radio-option"><input type="radio" name="paymentMethod" value="credit_card" ${state.paymentMethod==='credit_card'?'checked':''}><span><strong>Cartão de crédito</strong></span></label><label class="radio-option"><input type="radio" name="paymentMethod" value="debit_card" ${state.paymentMethod==='debit_card'?'checked':''}><span><strong>Cartão de débito</strong></span></label><label class="radio-option"><input type="radio" name="paymentMethod" value="cash" ${state.paymentMethod==='cash'?'checked':''}><span><strong>Dinheiro na entrega</strong></span></label></div></div>
      <div class="panel section"><h2>4. Cupom</h2><div class="discount-row section"><input class="field" name="coupon" value="${escapeHtml(state.coupon||'')}" placeholder="BEMVINDO10 ou FRETEGRATIS"><button type="button" class="secondary-btn" data-action="apply-coupon">Aplicar</button></div>${state.coupon?`<div class="notice section">Cupom informado: <strong>${escapeHtml(state.coupon)}</strong></div>`:''}</div>
      <div class="panel section"><h2>Resumo</h2><div class="summary section"><div class="summary-row"><span>Produtos (${this.cart.count()})</span><strong>${BRL(quote.subtotal)}</strong></div><div class="summary-row"><span>Desconto</span><strong>− ${BRL(quote.discount)}</strong></div><div class="summary-row"><span>Frete</span><strong>${BRL(quote.shippingCost)}</strong></div><div class="summary-row total"><span>Total</span><strong>${BRL(quote.total)}</strong></div></div><div class="order-actions"><button type="button" class="secondary-btn" data-action="back-cart">Voltar</button><button class="primary-btn" type="submit">Confirmar pedido</button></div></div>
    </form></section>`;
  }
  bind(root,state){const form=root.querySelector('#checkoutForm');form.addEventListener('change',e=>{if(['shipping','paymentMethod'].includes(e.target.name))this.handlers.onState({...state,[e.target.name]:e.target.value},false)});root.querySelector('[data-action="apply-coupon"]')?.addEventListener('click',()=>this.handlers.onState({...state,coupon:new FormData(form).get('coupon')||''},true));root.querySelector('[data-action="back-cart"]')?.addEventListener('click',()=>this.handlers.onBack());form.addEventListener('submit',e=>{e.preventDefault();const data=Object.fromEntries(new FormData(form));this.handlers.onSubmit({...state,customer:{name:data.name,email:data.email,phone:data.phone,address:data.address,number:data.number,city:data.city,zip:data.zip},shipping:data.shipping,paymentMethod:data.paymentMethod,coupon:data.coupon});});}
}
function quoteStandard(quote,state){return state.shipping==='standard'?quote.shippingCost:14.9}
